--- 
- 
  name: "install updates"
  yum: 
    name: "*"
    state: latest
- 
  name: "Install wget and git"
  yum: 
    name: 
      - git
      - wget
- 
  get_url: 
    dest: /etc/yum.repos.d/jenkins.repo
    url: "http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"
  name: "Download jenkins.repo"
- 
  name: "Import Jenkins Key"
  rpm_key: 
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    state: present
- 
  name: "Install Jenkins"
  yum: 
    name: jenkins
    state: present
- 
  name: "Start & Enable Jenkins"
  systemd: 
    enabled: true
    name: jenkins
    state: started
- 
  name: "Sleep for 30 seconds and continue with play"
  wait_for: timeout=30
- 
  changed_when: false
  name: "Get init password Jenkins"
  register: result
  shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
- 
  debug: 
    var: result.stdout
  name: "Print init password Jenkins"
